### ISSUE TITLE
New 4K compresion

### ISSUE THREAD

**Issue by StanekO** [kochd/electricsheep-hd-client#26]
Can you please check: electricsheep.244.00248.00774_electricsheep.244.00248.00774.webm = 19MB
It seems compresion is too agresive, at all new *.webms
On the other way, electricsheep.244.00241.01846_electricsheep.244.00242.01851.webm = 540MB is hardcore. But the new compression level looks not good, please check it on some 4k monitor..

**Comment by kochd** [comment]
Hi Stanek,

00774 is just an ugly genome. We got a few of them. Vote them down.
The jpegs look just the same:
![electricsheep 244 00248 00774_electricsheep 244 00248 00774](https://user-images.githubusercontent.com/1825660/64901144-718cc480-d696-11e9-98f1-af0b3ad48174.jpeg)

I already tweaked electricsheep.244.00241.01846_electricsheep.244.00242.01851 and its down to 178 MB. Its just hard to compress due to the way it moves.

I am still tweaking on this stuff: 

Sometimes you have sequences which are just not suitable. You need to find a compromise between too low bitrate (looks ugly and highly compressed) and too high bitrate (drops frames, stutters while being played).
At the moment we are targeting 24Mbit/s for the GPU. At 15 seconds playback a file size of 15*(24/8)=45MB is targeted. If the files are smaller than that there just wasn't need for a higher bitrate. If the files are larger than that the econder hit a deadline because you could easily compute for hours on compressing the the targeted size without success so when deadline is hit the data gets into the file 'as is' that is what happenes for electricsheep.244.00241.01846_electricsheep.244.00242.01851. This also means that player needs to be able to decode 3MB/s in order to play without any frame drops. Just making files larger leads to other problems when playing them. 

24MBits plays well for me and electricsheep.244.00258.10316_electricsheep.244.00259.00695 is currently rendering with 32MBit/s 15*(32/8)=60MB. If 32Mbits does not result in frame drops on non high-end hardware we will stick with it.

**Comment by StanekO** [comment]
So my configuration:
NAS 4T -> 1GLAN -> Intel HD630 & GTX 1050Ti -> Thunderbolt 3 -> 43" LG 43UD79-B
I have experience video min 720p, 1080p better.
I have experience with Interstellar.m2ts; 2:49h; 87GB; (64000kb/s) looks amazing.

Yours HD are perfect on HD
But doesn look good on 4k, they are not sharp and thre are fragments/Compression artifacts. So I was loking for 4k :-)

![18](https://user-images.githubusercontent.com/29358013/64909189-3c6d8a00-d709-11e9-9525-eac061ca3343.jpg)
"A" = electricsheep.244.00248.00774_electricsheep.244.00248.00774.webm = 19MB
there is 99% lost of texture in .webm becouse of low compresion

![243](https://user-images.githubusercontent.com/29358013/64909419-18f80e80-d70c-11e9-9778-7044f548b920.jpg)
"B" = electricsheep.244.00074.06306_electricsheep.244.00074.06306.webm = 242MB
perfect, sharp, looks amazing.

![527](https://user-images.githubusercontent.com/29358013/64909213-6e7eec00-d709-11e9-924b-49ab3013f2e1.jpg)
"C" = electricsheep.244.00241.01846_electricsheep.244.00242.01851.webm = 527MB
It seam i7-7700HQ & Intel HD 630 & VLC is this video neer HW limit. Peak is (420 000kb/s) But is sharp and really detailed..
(I don know, why is VLC not using Nvidia 1050 or if there is missing HW acceleration for vp9, but does not matter on it)..

![70](https://user-images.githubusercontent.com/29358013/64909220-89e9f700-d709-11e9-8952-d38b9239b50c.jpg)
"C.2" = electricsheep.244.00241.01846_electricsheep.244.00242.01851.webm = 71MB
I am sorry, but is really disappoint, you can see fragments and distortion in lot of sektors..

The point is, I think, video output for 4K bitrate = 24 MBit/s is looking really bad with comparison of last compression level. I can accept the large file size, but loss of image quality is a problem. If HD are looking better than 4K, because of large video bitrate compression :-)

I am waiting for download: electricsheep.244.00258.10316_electricsheep.244.00259.00695 to check 32MBit/s output..
Thanks

**Comment by kochd** [comment]
>   "C.2" = electricsheep.244.00241.01846_electricsheep.244.00242.01851.webm = 71MB
> I am sorry, but is really disappoint, you can see fragments and distortion in lot of sektors..

I am currently @104MBits as limit (avg. maximum file size of: 195MB) which isn't reached by the encoder and everything was deleted and is re-rendering now. If you delete your local *.webms you will get the updated once as soon as they are available. 
![mpv-shot0009](https://user-images.githubusercontent.com/1825660/64914522-f4278980-d753-11e9-8687-1f8f44f7df7a.jpg)


Keep in mind that there is a deadline problem:
The output of webms must be greater than the input of frames. For that reason the job queue auto tunes how much cpu time to spend on rendering. When there are less jobs in the queue more time is spend for optimizations:
<pre>                                                                                                                                                                                                                                                      
    tunefactor = 4                                                                                                                                                                                                                                                              
    if $jobs.count/tunefactor <= 0                                                                                                                                                                                                                                              
      tune = 1                                                                                                                                                                                                                                                                  
    elsif $jobs.count <= tunefactor*8                                                                                                                                                                                                                                           
      tune = $jobs.count/tunefactor                                                                                                                                                                                                                                             
    else                                                                                                                                                                                                                                                                        
      tune = 8                                                                                                                                                                                                                                                                  
    end                                                                                           
...
              # (as used by libvpx)
              "cpu_used"       => tune, # Less is better: More CPU used                                                                
              "speed"          => tune*2, # Less is better: More CPU used  
</pre>
32 or more queued jobs result in the fastest rendering mode while just 4 or less results in almost the slowest. Rendering slower of course gives the best result but time is a limiting factor here because sometimes you need to trade speed for quality to keep up with the input.

**Comment by kochd** [comment]
I think i've dialed it in now. Check out the results since electricsheep.244.00249.10308_electricsheep.244.00249.10308

**Comment by StanekO** [comment]
Yes, from 244.00249.... it looks perfect. 
Thank you..

<img width="1052" alt="Poznámka 2019-09-15 200358" src="https://user-images.githubusercontent.com/29358013/64925638-fe996000-d7f3-11e9-99a1-fb5142b320f9.png">
[https://docs.google.com/spreadsheets/d/1d6UC7SdVw898Vsj7atNu430l9Jjw1K0RvAiwg3uLvSg/edit?usp=sharing](table)

**Comment by kochd** [comment]
I've deleted:
<pre>
electricsheep.244.00241.01846_electricsheep.244.00242.01851.webm
electricsheep.244.00241.01846_electricsheep.244.00241.01846.webm
electricsheep.244.00240.00860_electricsheep.244.00240.00860.webm
electricsheep.244.00239.01046_electricsheep.244.00240.00860.webm
electricsheep.244.00239.01046_electricsheep.244.00239.01046.webm
</pre>

these are the once from your sheet which suffered from econding. They will be rendered now with better settings.

**Comment by StanekO** [comment]
PS. I have found a last one: 
electricsheep.244.00282.00324_electricsheep.244.00282.00324.webm = 1000Mb (bitrate 600000 kb/s)
I download [https://www.webmproject.org](www.webmproject.org) to try resample.. But I am not success to setup working command.. What configuration are you using, can you share sample to setup parameters?
`makewebm.exe --input "..." --output "...\test.webm" --encoder VP9 --target-bitrate=60000 --noise-sensitivity 0 --thread-count 7 --end-usage CBR --no-audio --passes 1`

**Comment by kochd** [comment]
I use ffmpeg.
Due to the complexity this is setup i can not give you just an simple command line to reproduce.
The reason why that file is so large is because its hard to compress and libvpx runs in cq mode. To keep the desired quality it has to overshoot the targeted bitrate by that immense factor. 
If you look at that file you'll see that its just a ton of noise and so are the raw frames:
https://sheeps.triple6.org/frame/G244_W3840_H2160_Q1024_KY38402AGPU/electricsheep.244.00282.00324_electricsheep.244.00282.00324

Someone was joking when uploading that genome. -,-
that thing cant be compressed and is already down voted and will never ever be used again.

**Comment by kochd** [comment]
Here's what gets passed to ffmpeg:
```ruby
{"nframes"=>360, "fps"=>24, "encoder"=>"libvpx-vp9", "crf"=>18, "qmin"=>4, "qmax"=>39, "bitrate"=>"52M", "maxrate"=>"52M", "minrate"=>"100k", "cpu_used"=>1, "speed"=>2, "deadline"=>"good", "auto-alt-ref"=>1, "arnr-maxframes"=>7, "arnr-strength"=>5, "arnr-type"=>"centered", "pix_fmt"=>"yuv422p", "filters"=>nil}
```

**Comment by StanekO** [comment]
OK
`ffmpeg -i "D:\Programy\Electric Sheep HD\branches\G244_W3840_H2160_Q1024_KY38402AGPU\electricsheep.244.00282.00324_electricsheep.244.00282.00324.webm" -c:v libvpx-vp9 -minrate 500k -b:v 90000k -maxrate 130000k "D:\Programy\Electric Sheep HD\branches\G244_W3840_H2160_Q1024_KY38402AGPU\test4.webm"`
You can replace sheep with LOW resolution (150MB), if you want to save Space & Internet Connection: 
Download: [https://uloz.to/file/4Qfc7Y95PmM8/electricsheep-244-00282-00324-electricsheep-244-00282-00324-webm](url)
Delete: [https://uloz.to/smazat/4Qfc7Y95PmM8/8821235391017077760](url)
