### ISSUE TITLE
Missing entries from request_sequence_list

### ISSUE THREAD

**Issue by EricChiz** [kochd/electricsheep-hd-client#71]
Since the server upgrade at the end of February, request_sequence_list returns a list containing gaps between sequence 818 and 978, with absolutely no sequences between 825 and 975.

I can generate a full list of the missing sequences if it's needed.

**Comment by kochd** [comment]
As disk space is endless and limited to 600GB with the current server, it has to delete stored sequence from time to time in order to make free space for new sequences.
Punching a hole in between was clearly not intended and I am unsure why exactly this happened during the update.
But deleting rendered sequences from the server when disk space is rare is a desired behavior.
