### ISSUE TITLE
What would it take to increase upload capacity?

### ISSUE THREAD

**Issue by Aquaritek** [kochd/electricsheep-hd-client#80]
Hey Kochd,

I'm wondering, how much exactly would it take to run a higher capacity (bandwidth) server for the uploads? 

Also, and something a little more arduous. would be my thoughts on a node here in the US. I however have no idea what the backend architecture looks like now so won't even speak to that currently.

With peace, Aqua.

**Comment by kochd** [comment]
Hi Aqua,

> I'm wondering, how much exactly would it take to run a higher capacity (bandwidth) server for the uploads?

What's your point of view when talking about UPload?
So that the server is able to receive the frames from clients faster?:

The project is running a vserver which shares it's bandwidth with other customers of the vserver provider.
This means the bandwidth it has available is not deterministic at a any given time.

https://www.hetzner.com/dedicated-rootserver/ax41-nvme?country=us
For a real dedicated root server you pay >2x the price per month.

The same applies for the other way around: "Downloading webm's faster"

This is the optional goal. but we didn't manage to get the 15€/month to sustain the minimal setup for 2021. So basically I paid for the difference in cost vs. donations.: 
https://sheeps.triple6.org/donate 

This is the current profile:

```
                     rx      |     tx      |    total    |   avg. rate
     ------------------------+-------------+-------------+---------------
       Jan '22    225,68 GiB |  561,00 GiB |  786,68 GiB |    9,91 Mbit/s
     ------------------------+-------------+-------------+---------------
     estimated    907,93 GiB |    2,20 TiB |    3,09 TiB |
```

The vserver provider probably hates us because we produce an over the average amount of traffic compared to the average low cost vserver customer. 

> Also, and something a little more arduous. would be my thoughts on a node here in the US. I however have no idea what the backend architecture looks like now so won't even speak to that currently.


I don't think that is cost efficient.
You usually use edge nodes for applications that require low latency which isn't the case here. 
We would just need more bandwidth no matter where it is located.

**Comment by Aquaritek** [comment]
Ultimately yes it would be for the uploads. Ultimately I tend to get a lot of 502's due to my ability to saturate the pipe. I extended the error handling of that section to retry uploads so that it doesn't back out and skip frames.

I'm wondering, would you accept a crypto donation?

**Comment by Aquaritek** [comment]
I'm willing to get the project server upgraded for at-least the next year to the dedicated root server you listed above if you believe that will greatly increase the bandwidth for uploads and downloads. I also assume this would increase the storage capacity for the server to hold flames and also increase the speed of the website am I correct?

I can send in really any standard stable coin, USDT, USDC, PAX, TUSD, DAI etc. Thinking $500 would get some good runway. That's what 440 Euro or there abouts.
